name: oneride test
favicon: null
layout_spectrum: 0.8873688897583634
typography_spectrum: 0.8355012617539614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2474541123956442
  lightness: 0.9193842501845211
  saturation: 0.7637554435059428
  rhythmicContrast: 0.22662720503285527
purpose: []
